2019-11-10.00:25:02 ERROR [main] com.niit.web.blog.dao.MainDaoTest.batchInsert:44  批量新增用户出现异常
